const iataCodes = {
  "New York": "NYC",
  London: "LON",
  "Los Angeles": "LAX",
  Chicago: "CHI",
  Paris: "PAR",
  Tokyo: "TYO",
  "San Francisco": "SFO",
  "Hong Kong": "HKG",
  Sydney: "SYD",
  Toronto: "YTO",
  Vancouver: "YVR",
  Berlin: "BER",
  Frankfurt: "FRA",
  Munich: "MUC",
  Amsterdam: "AMS",
  Dubai: "DXB",
  Singapore: "SIN",
  Bangkok: "BKK",
  "Kuala Lumpur": "KUL",
  "Cape Town": "CPT",
  Johannesburg: "JNB",
  Moscow: "MOW",
  Istanbul: "IST",
  Rome: "ROM",
  Madrid: "MAD",
  Barcelona: "BCN",
  Athens: "ATH",
  Dublin: "DUB",
  Zurich: "ZRH",
  Geneva: "GVA",
  Vienna: "VIE",
  Brussels: "BRU",
  Stockholm: "STO",
  Oslo: "OSL",
  Copenhagen: "CPH",
  Helsinki: "HEL",
  Lisbon: "LIS",
  Warsaw: "WAW",
  Budapest: "BUD",
  Prague: "PRG",
  "Abu Dhabi": "AUH",
  Doha: "DOH",
  Riyadh: "RUH",
  Jeddah: "JED",
  Beijing: "BJS",
  Shanghai: "SHA",
  Guangzhou: "CAN",
  Seoul: "SEL",
  Mumbai: "BOM",
  Delhi: "DEL",
  Bangalore: "BLR",
  Chennai: "MAA",
  Manila: "MNL",
  Jakarta: "CGK",
  "Ho Chi Minh": "SGN",
  Saigon: "SGN",
  Melbourne: "MEL",
  Brisbane: "BNE",
  Auckland: "AKL",
};

export default iataCodes;
